export type EvidenceLevel = 'Mạnh' | 'Vừa' | 'Hỗn hợp';

export type KnowledgeField = {
  id: string;
  short: string;
  title: string;
  eyebrow: string;
  accent: string;
  evidence: EvidenceLevel;
  evidenceNote: string;
  summary: string;
  image: string;
  imagePosition?: string;
  alt: string;
  credit: string;
  imageSource: string;
  visualNotes: string[];
  quickFacts: { label: string; value: string }[];
  principleTitle: string;
  process: { title: string; text: string }[];
  milestones: { date: string; place: string; text: string }[];
  legacies: string[];
  limits: string[];
  sources: { label: string; url: string }[];
};

export const knowledgeFields: KnowledgeField[] = [
  {
    id: 'thien-van',
    short: 'Thiên văn',
    title: 'Thiên văn & lịch pháp',
    eyebrow: 'Đo thời gian bằng bầu trời',
    accent: '#a13b2b',
    evidence: 'Mạnh',
    evidenceNote: 'Chu kỳ có thể tính lại và đối chiếu với cơ học thiên thể. Kết luận này chỉ áp dụng cho phép đo và lịch pháp, không áp dụng cho chiêm tinh hay điềm báo.',
    summary: 'Thiên văn và lịch pháp cổ hình thành từ những quan sát lặp lại Mặt Trời, Mặt Trăng, sao và mùa. Người xưa dùng cọc đo bóng, đường ngắm, đồng hồ nước và kiến trúc định hướng để lập lịch dân sự, lịch nông nghiệp và bảng dự tính nhật–nguyệt thực. Giá trị khoa học nằm ở dữ liệu dài hạn, số học chu kỳ và khả năng hiệu chỉnh sai lệch giữa tháng âm với năm dương.',
    image: '/images/01-astronomy.jpg',
    imagePosition: 'center 58%',
    alt: 'Thiên bàn phẳng bằng đồng Iran thế kỷ XVII với mạng sao, trục ngắm và các vòng chia độ thiên văn.',
    credit: 'Muhammad Zaman al-Munajjim al-Asturlabi, 1654–55 · The Met · CC0',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Planispheric_Astrolabe_MET_DP170383.jpg',
    visualNotes: ['Vòng chia độ', 'Mạng sao xoay', 'Trục ngắm'],
    quickFacts: [
      { label: 'Công cụ', value: 'Gnomon · Nhật quỹ · Tinh bàn' },
      { label: 'Dữ liệu', value: 'Bóng · Vị trí sao · Chu kỳ' },
      { label: 'Đầu ra', value: 'Lịch · Mùa vụ · Phương hướng' },
    ],
    principleTitle: 'Quan sát lặp lại biến chuyển động thành lịch.',
    process: [
      { title: 'Dựng mốc', text: 'Chọn chân trời, thiên cực, đường ngắm hoặc vật tạo bóng cố định.' },
      { title: 'Ghi vị trí', text: 'Đo thiên thể tại cùng thời điểm qua nhiều ngày, tháng và năm.' },
      { title: 'Tìm chu kỳ', text: 'Lập bảng số học để nhận ra mẫu lặp và sai lệch tích lũy.' },
      { title: 'Hiệu chỉnh', text: 'So dự tính với quan sát mới rồi thêm ngày, tháng nhuận hoặc cải lịch.' },
    ],
    milestones: [
      { date: '≈ 2450 TCN', place: 'Ai Cập', text: 'Lịch dân sự 12 tháng × 30 ngày, cộng 5 ngày cuối năm.' },
      { date: 'Thiên niên kỷ I TCN', place: 'Babylon', text: 'Nhật ký thiên văn trên bảng đất sét tạo dữ liệu kéo dài nhiều thế kỷ.' },
      { date: '104 TCN', place: 'Trung Hoa', text: 'Cải lịch Thái Sơ kết hợp đo sao chuẩn và hiệu chỉnh lịch.' },
      { date: '250–900', place: 'Maya', text: 'Haab, Tzolk’in và Long Count phối hợp chu kỳ với niên đại lịch sử.' },
    ],
    legacies: ['Hệ cơ số 60 trong phút, giây và 360 độ.', 'Nguyên tắc nhuận để đồng bộ lịch với chu kỳ trời.', 'Bản ghi cổ hỗ trợ định niên đại và nghiên cứu dài hạn.'],
    limits: ['Quan sát mắt thường và mô hình địa tâm giới hạn cách giải thích vật lý.', 'Suy đoán vận mệnh từ thiên thể không được dữ liệu thiên văn xác nhận.'],
    sources: [
      { label: 'The Met — đo thời gian ở Ai Cập', url: 'https://www.metmuseum.org/essays/telling-time-in-ancient-egypt' },
      { label: 'Smithsonian — hệ lịch Maya', url: 'https://maya.nmai.si.edu/calendar/calendar-system' },
    ],
  },
  {
    id: 'toan-hoc',
    short: 'Toán học',
    title: 'Toán học & hình học',
    eyebrow: 'Từ đo đất đến chứng minh',
    accent: '#3d6177',
    evidence: 'Mạnh',
    evidenceNote: 'Định lý và thuật toán có thể chứng minh, chạy lại và đối chiếu trực tiếp với văn bản còn tồn tại.',
    summary: 'Toán học cổ nảy sinh từ nhu cầu đếm, chia đất, xây dựng, thu thuế và quan sát bầu trời. Mesopotamia phát triển bảng tính cơ số 60; Hy Lạp nhấn mạnh chứng minh suy diễn; Trung Hoa dùng que tính và thuật toán; Ấn Độ hoàn thiện hệ vị trí, số không và số âm. Nhiều kết quả vẫn đúng hoàn toàn, nhưng không nên gán ký hiệu hay khái niệm hiện đại nguyên vẹn cho người cổ.',
    image: '/images/02-mathematics.jpg',
    imagePosition: 'center',
    alt: 'Trang in Cơ sở của Euclid năm 1482 với các sơ đồ hình học đặt bên lề văn bản.',
    credit: 'Erhard Ratdolt, Euclid’s Elements, 1482 · Library of Congress · Public domain',
    imageSource: 'https://www.loc.gov/pictures/item/2005683646/',
    visualNotes: ['Tiền đề', 'Hình dựng', 'Kết luận'],
    quickFacts: [
      { label: 'Biểu diễn', value: 'Chữ số · Que tính · Hình vẽ' },
      { label: 'Phương pháp', value: 'Thuật toán · Suy diễn · Kiểm tra' },
      { label: 'Di sản', value: 'Số 0 · Hình học · Đại số tuyến tính' },
    ],
    principleTitle: 'Biến việc thực thành quan hệ có thể kiểm tra.',
    process: [
      { title: 'Biểu diễn', text: 'Đưa lượng vào chữ số, đơn vị, bảng, que tính hoặc hình.' },
      { title: 'Mô hình hóa', text: 'Chuyển bài toán thực tế thành quan hệ số học hay hình học.' },
      { title: 'Suy giải', text: 'Áp dụng thuật toán hữu hạn hoặc suy diễn từ tiền đề.' },
      { title: 'Kiểm tra', text: 'Dùng phép tính ngược, ví dụ hoặc chứng minh để xác nhận.' },
    ],
    milestones: [
      { date: '2000–1700 TCN', place: 'Babylon', text: 'Hệ vị trí cơ số 60, bảng nghịch đảo và thủ tục tương đương giải bậc hai.' },
      { date: '≈ 300 TCN', place: 'Alexandria', text: 'Euclid hệ thống hóa hình học từ định nghĩa, tiên đề và chứng minh.' },
      { date: '≈ 200 TCN–50', place: 'Trung Hoa', text: 'Cửu chương trình bày 246 bài toán và thao tác tương tự phép khử.' },
      { date: '628', place: 'Ấn Độ', text: 'Brahmagupta nêu quy tắc với số không và số âm.' },
    ],
    legacies: ['Phân chia giờ và góc theo cơ số 60.', 'Phương pháp tiên đề–chứng minh của toán học hiện đại.', 'Hệ vị trí, số 0 và thuật toán giải hệ tuyến tính.'],
    limits: ['Ký hiệu chưa thống nhất khiến nhiều quy tắc khó tổng quát hóa.', 'Một số giá trị gần đúng và quy tắc cổ — như chia cho 0 — không đúng.'],
    sources: [
      { label: 'MacTutor — toán Babylon', url: 'https://mathshistory.st-andrews.ac.uk/HistTopics/Babylonian_mathematics/' },
      { label: 'MacTutor — Cửu chương', url: 'https://mathshistory.st-andrews.ac.uk/HistTopics/Nine_chapters/' },
      { label: 'MacTutor — Brahmagupta', url: 'https://mathshistory.st-andrews.ac.uk/Biographies/Brahmagupta/' },
    ],
  },
  {
    id: 'y-duoc',
    short: 'Y dược',
    title: 'Y dược & dược liệu',
    eyebrow: 'Kinh nghiệm chữa trị phải qua kiểm chứng',
    accent: '#577044',
    evidence: 'Hỗn hợp',
    evidenceNote: 'Một số hoạt chất và can thiệp có lợi ích; nhiều công thức hoặc chỉ định chưa được thử nghiệm đầy đủ. Hệ lý thuyết cổ không mặc nhiên là mô hình sinh học đã chứng minh.',
    summary: 'Y dược cổ lưu giữ quan sát về triệu chứng, vết thương, cây thuốc, chế độ ăn và kỹ thuật chăm sóc. Dược liệu là nguồn gợi ý quan trọng cho nghiên cứu hoạt chất, không phải bằng chứng tự động về hiệu quả: đúng loài, bộ phận, liều, độc tính và tương tác đều phải được kiểm tra. Mỗi phương pháp nên được đánh giá riêng bằng dữ liệu hiện đại, thay vì xác nhận hoặc bác bỏ cả một truyền thống chỉ vì tuổi đời của nó.',
    image: '/images/03-medicine.jpg',
    imagePosition: 'center',
    alt: 'Trang bản thảo dược học thế kỷ XIII vẽ cây thuốc và chú giải bằng chữ Ả Rập.',
    credit: 'Page from an Herbal Manuscript, thế kỷ XIII · LACMA · Public domain',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Page_from_an_Herbal_Manuscript_LACMA_M.73.5.407a-b_%283_of_3%29.jpg',
    visualNotes: ['Nhận dạng loài', 'Bộ phận dùng', 'Liều & độc tính'],
    quickFacts: [
      { label: 'Đầu vào', value: 'Triệu chứng · Dược liệu · Chế độ ăn' },
      { label: 'Kiểm chứng', value: 'Hóa học · Lâm sàng · Cảnh giác dược' },
      { label: 'Nguyên tắc', value: 'Đánh giá từng thuốc, từng chỉ định' },
    ],
    principleTitle: 'Quan sát tạo giả thuyết; thử nghiệm quyết định hiệu quả.',
    process: [
      { title: 'Nhận dạng', text: 'Quan sát người bệnh và xác định chính xác nguyên liệu.' },
      { title: 'Chế biến', text: 'Phơi, nghiền, sắc hoặc ngâm với liều và quy trình rõ.' },
      { title: 'Theo dõi', text: 'Ghi đáp ứng, tác dụng bất lợi và diễn tiến bệnh.' },
      { title: 'Kiểm chứng', text: 'Phân tích hoạt chất, thử nghiệm lâm sàng và giám sát an toàn.' },
    ],
    milestones: [
      { date: '2000–1500 TCN', place: 'Ai Cập', text: 'Các giấy cói ghi vết thương, thủ thuật và phương thuốc cùng cả yếu tố ma thuật.' },
      { date: '430–330 TCN', place: 'Hy Lạp', text: 'Bộ Hippocrates nhấn mạnh quan sát diễn tiến bệnh và nguyên nhân tự nhiên.' },
      { date: 'Thiên niên kỷ I TCN', place: 'Ấn Độ', text: 'Charaka và Sushruta hệ thống hóa nội khoa, dược liệu và phẫu thuật.' },
      { date: '25–220', place: 'Trung Hoa', text: 'Thần Nông bản thảo kinh phân loại 365 dược liệu và độc tính.' },
    ],
    legacies: ['Khám lâm sàng, ghi bệnh án và theo dõi diễn tiến.', 'Dược điển và thực vật dân tộc hỗ trợ tìm hoạt chất.', 'Một số chăm sóc vết thương và can thiệp giảm đau có giá trị riêng.'],
    limits: ['Khí, kinh lạc, dosha và bốn thể dịch chưa được xác nhận như cơ chế sinh học.', 'Dược liệu có thể sai loài, sai liều, tương tác thuốc hoặc chứa chất độc.'],
    sources: [
      { label: 'NCCIH — y học Trung Hoa: bằng chứng và an toàn', url: 'https://www.nccih.nih.gov/health/traditional-chinese-medicine-what-you-need-to-know' },
      { label: 'WHO — đánh giá y học truyền thống', url: 'https://www.who.int/publications/i/item/9789241506090' },
    ],
  },
  {
    id: 'nong-hoc',
    short: 'Nông học',
    title: 'Nông học',
    eyebrow: 'Phòng thí nghiệm kéo dài qua nhiều mùa vụ',
    accent: '#6f6a35',
    evidence: 'Mạnh',
    evidenceNote: 'Hiệu quả của luân canh, vật chất hữu cơ, giữ đất và quản lý nước có thể đo được. Kết quả của từng hệ truyền thống vẫn phụ thuộc địa điểm.',
    summary: 'Nông học cổ là tập hợp kỹ thuật thuần hóa, chọn giống, quản lý nước, giữ đất, bón hữu cơ, xen canh và bảo quản lương thực. Người trồng so sánh giống, mưa, đất, sâu bệnh và năng suất qua nhiều vụ rồi lưu truyền hạt giống cùng quy trình phù hợp địa phương. Kênh tưới, qanat, ruộng bậc thang và chinampa cho thấy kỹ thuật luôn gắn với tổ chức cộng đồng và giới hạn sinh thái.',
    image: '/images/04-agriculture.jpg',
    imagePosition: 'center',
    alt: 'Tiểu họa thế kỷ XV mô tả người làm vườn thu hoạch bắp cải trong các luống cây.',
    credit: 'Tacuinum Sanitatis, thế kỷ XV · BnF/Gallica · Public domain',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Tacuinum_Sanitatis-cabbage_harvest.jpg',
    visualNotes: ['Chọn giống', 'Giữ đất & nước', 'Thu hoạch'],
    quickFacts: [
      { label: 'Hệ thống', value: 'Giống · Đất · Nước · Cộng đồng' },
      { label: 'Chu kỳ', value: 'Gieo · Theo dõi · Chọn hạt' },
      { label: 'Rủi ro', value: 'Mặn hóa · Xói mòn · Suy đất' },
    ],
    principleTitle: 'Mỗi vụ mùa là một vòng quan sát và chọn lọc.',
    process: [
      { title: 'Đọc nơi chốn', text: 'Đánh giá đất, nước, mùa và chọn giống phù hợp.' },
      { title: 'Tổ chức ruộng', text: 'Phối hợp luân canh, xen canh hoặc cây với vật nuôi.' },
      { title: 'Điều tiết', text: 'Quản lý nước, dinh dưỡng và sâu bệnh trong suốt vụ.' },
      { title: 'Chọn & lưu', text: 'Thu hoạch, giữ hạt tốt rồi điều chỉnh cho vụ sau.' },
    ],
    milestones: [
      { date: '≈ 10.000 năm trước', place: 'Lưỡi liềm Màu mỡ', text: 'Ngũ cốc và cây họ đậu được thuần hóa qua chọn lọc kéo dài.' },
      { date: 'Thiên niên kỷ IV–III TCN', place: 'Mesopotamia', text: 'Kênh tưới và cày mở rộng canh tác nhưng cũng tạo bài toán mặn hóa.' },
      { date: 'Ít nhất ≈ 800 TCN', place: 'Iran', text: 'Qanat dẫn nước ngầm bằng trọng lực và giảm bốc hơi.' },
      { date: 'Trước thế kỷ XVI', place: 'Mexico', text: 'Chinampa kết hợp luống nổi, bùn màu mỡ và mạng kênh.' },
    ],
    legacies: ['Chọn giống và bảo tồn giống địa phương.', 'Tưới trọng lực, ruộng bậc thang và công trình giữ đất–nước.', 'Luân canh cây họ đậu, xen canh và hoàn trả hữu cơ.'],
    limits: ['Kỹ thuật địa phương không thể sao chép nguyên trạng sang mọi nơi.', 'Tưới kém thoát nước, phát quang hoặc cày liên tục có thể làm suy đất.'],
    sources: [
      { label: 'FAO — hệ qanat Kashan', url: 'https://www.fao.org/family-farming/detail/en/c/283205/' },
      { label: 'FAO — hệ chinampa', url: 'https://www.fao.org/giahs/giahs-around-the-world/mexico-chinampas-agricultural-system/en' },
    ],
  },
  {
    id: 'kien-truc',
    short: 'Kiến trúc',
    title: 'Kiến trúc & kỹ thuật',
    eyebrow: 'Dẫn lực, nước, gió và nhiệt',
    accent: '#8a5435',
    evidence: 'Mạnh',
    evidenceNote: 'Cấu trúc, vật liệu và thủy lực có thể đo hoặc mô phỏng trực tiếp. Một số chi tiết thi công và tổ chức lao động vẫn là phục dựng.',
    summary: 'Kiến trúc và kỹ thuật cổ kết hợp hình học, tri thức vật liệu, tổ chức lao động và kinh nghiệm về tải trọng, nước, gió cùng nhiệt. Mô-đun gạch, mộng gỗ, cột–dầm, vòm, bê tông vôi và độ dốc nhỏ tạo nên công trình bền hoặc hệ dẫn nước xa mà không cần động cơ. Công trình còn đứng là bằng chứng mạnh, nhưng cũng tạo thiên lệch sống sót: vô số thử nghiệm thất bại đã biến mất.',
    image: '/images/05-architecture.jpg',
    imagePosition: 'center',
    alt: 'Cầu dẫn nước Pont du Gard ba tầng vòm đá bắc qua sông, vận chuyển nước bằng trọng lực.',
    credit: 'Pont du Gard · Ảnh Pierre Blaché · CC0',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Pont_du_Gard,_France.jpg',
    visualNotes: ['Vòm truyền lực', 'Độ dốc rất nhỏ', 'Dòng chảy trọng lực'],
    quickFacts: [
      { label: 'Kết cấu', value: 'Cột–dầm · Vòm · Mái vòm' },
      { label: 'Hạ tầng', value: 'Giếng · Cống · Cầu dẫn nước' },
      { label: 'Khí hậu', value: 'Nắng · Gió · Khối nhiệt' },
    ],
    principleTitle: 'Hình học dẫn tải; địa hình dẫn dòng.',
    process: [
      { title: 'Khảo sát', text: 'Đọc địa hình, nền đất, nắng–gió và lập trục chuẩn.' },
      { title: 'Chọn hệ', text: 'Ghép vật liệu, mô-đun và kiểu liên kết phù hợp.' },
      { title: 'Dẫn lực', text: 'Dùng cột–dầm, vòm–cuốn, tường chống hoặc độ dốc.' },
      { title: 'Bảo trì', text: 'Tổ chức trình tự thi công, thoát nước và kiểm tra định kỳ.' },
    ],
    milestones: [
      { date: 'XXVII–XXVI TCN', place: 'Ai Cập', text: 'Kim tự tháp cho thấy khảo sát, khai thác đá và hậu cần quy mô lớn.' },
      { date: 'Thiên niên kỷ III TCN', place: 'Mohenjo-daro', text: 'Đường vuông góc, giếng, gạch nung và mạng thoát nước đô thị.' },
      { date: 'Thiên niên kỷ I TCN', place: 'Ba Tư', text: 'Qanat dẫn nước qua hầm có độ dốc nhỏ; một số hệ vẫn hoạt động.' },
      { date: 'Thế kỷ I TCN–II', place: 'La Mã', text: 'Vòm, bê tông và cầu dẫn nước đạt quy mô lớn.' },
    ],
    legacies: ['Vòm, cuốn và mái vòm trong thiết kế kết cấu.', 'Cấp–thoát nước trọng lực và quy hoạch vệ sinh đô thị.', 'Thiết kế thụ động theo nắng, gió và khối nhiệt.'],
    limits: ['Quy tắc kinh nghiệm không thay thế tính tải và chuẩn động đất hiện đại.', 'Độ bền kỹ thuật không tự chứng minh tính bền vững xã hội hay môi trường.'],
    sources: [
      { label: 'UNESCO — Mohenjo-daro', url: 'https://whc.unesco.org/en/list/138' },
      { label: 'UNESCO — qanat Ba Tư', url: 'https://whc.unesco.org/en/list/1506/' },
      { label: 'UNESCO — Pont du Gard', url: 'https://whc.unesco.org/en/list/344/' },
    ],
  },
  {
    id: 'luyen-kim',
    short: 'Luyện kim',
    title: 'Luyện kim & vật liệu',
    eyebrow: 'Điều khiển nhiệt để biến đổi vật chất',
    accent: '#a25e24',
    evidence: 'Mạnh',
    evidenceNote: 'Xỉ, lò, quặng và vi cấu trúc xác nhận trực tiếp nhiều quy trình. Tranh luận chủ yếu nằm ở niên đại sớm nhất và đường truyền công nghệ.',
    summary: 'Luyện kim cổ biến quặng thành vật liệu mới bằng nhiệt, phản ứng khử, hợp kim hóa, đúc, rèn và xử lý nhiệt — khác với mục tiêu huyền bí của giả kim thuật. Không có nhiệt kế hay giản đồ pha, thợ cổ dựa vào màu lò, luồng gió, loại than, xỉ và tốc độ nguội. Khảo cổ học hiện đại đọc lại quy trình ấy qua lò, khuôn, xỉ và vi cấu trúc kim loại.',
    image: '/images/06-metallurgy.jpg',
    imagePosition: 'center',
    alt: 'Tranh khắc gỗ năm 1556 mô tả thợ nung, đập và xử lý kim loại trong xưởng luyện.',
    credit: 'Georgius Agricola, De re metallica, 1556 · Public domain',
    imageSource: 'https://commons.wikimedia.org/wiki/File:De_re_metallica_p_391.jpg',
    visualNotes: ['Quặng & than', 'Lò hoàn nguyên', 'Rèn & xử lý nhiệt'],
    quickFacts: [
      { label: 'Biến đổi', value: 'Khử · Hợp kim · Kết tinh' },
      { label: 'Kỹ thuật', value: 'Đúc · Rèn · Tôi · Ram' },
      { label: 'Dấu vết', value: 'Lò · Xỉ · Khuôn · Vi cấu trúc' },
    ],
    principleTitle: 'Nhiệt, carbon và tốc độ nguội quyết định vật liệu.',
    process: [
      { title: 'Tuyển quặng', text: 'Tìm, đập và đôi khi nung sơ nguyên liệu.' },
      { title: 'Hoàn nguyên', text: 'Cấp than và gió để đạt nhiệt cùng môi trường khử.' },
      { title: 'Tách & tạo hình', text: 'Loại xỉ rồi đúc hợp kim hoặc rèn đặc khối sắt.' },
      { title: 'Xử lý nhiệt', text: 'Ủ, tôi, ram và làm nguội để chỉnh độ cứng–dẻo.' },
    ],
    milestones: [
      { date: 'Thiên niên kỷ V TCN', place: 'Balkan & Tây Á', text: 'Luyện đồng từ khoáng vật xuất hiện cạnh kỹ thuật dùng đồng tự sinh.' },
      { date: '≈ 2800 TCN', place: 'Mesopotamia', text: 'Pha đồng với thiếc tạo bronze dễ đúc và thường cứng hơn.' },
      { date: '1700–221 TCN', place: 'Trung Hoa', text: 'Khuôn đất ghép tạo đồ đồng rỗng và hoa văn phức tạp.' },
      { date: 'V TCN–I', place: 'Đông & Nam Á', text: 'Gang, tinh luyện gang và thép carbon cao phát triển theo các tuyến riêng.' },
    ],
    legacies: ['Nguyên lý hoàn nguyên quặng và kiểm soát lò.', 'Thiết kế hợp kim, khuôn đúc và tái chế kim loại.', 'Xử lý nhiệt để điều khiển vi cấu trúc và cơ tính.'],
    limits: ['Thiếu đo nhiệt và thành phần khiến chất lượng giữa các mẻ biến động.', 'Khai mỏ và than củi gây độc hại, phá rừng và ô nhiễm.'],
    sources: [
      { label: 'Historic England — khảo cổ luyện kim', url: 'https://historicengland.org.uk/images-books/publications/archaeometallurgy-guidelines-best-practice/' },
      { label: 'British Museum — kỹ thuật đồng Trung Hoa', url: 'https://www.britishmuseum.org/sites/default/files/2019-10/Chinese-Art-Teachers-guide.pdf' },
    ],
  },
  {
    id: 'hang-hai',
    short: 'Hàng hải',
    title: 'Hàng hải & định hướng',
    eyebrow: 'Biến đại dương thành một bản đồ sống',
    accent: '#2d6870',
    evidence: 'Mạnh',
    evidenceNote: 'Thiên văn, từ tính, sóng, dòng chảy và ước lượng vị trí đều kiểm chứng được. Độ chính xác phụ thuộc tuyến biển, môi trường và kỹ năng người dẫn đường.',
    summary: 'Hàng hải cổ là một hệ thống quan sát, ghi nhớ và kiểm tra chéo. Người dẫn đường Thái Bình Dương dùng sao trên chân trời, hướng sóng, gió, mây, chim và dấu hiệu đảo; thủy thủ Ấn Độ Dương kết hợp mùa gió với độ cao sao; Trung Hoa và Địa Trung Hải bổ sung la bàn, hải trình và hải đồ. Kỹ thuật hiệu quả nhất khi gắn với tuyến, mùa và kinh nghiệm địa phương.',
    image: '/images/07-navigation.jpg',
    imagePosition: 'center',
    alt: 'Bản đồ que Marshall bằng que, sợi và vỏ sò mã hóa hướng sóng, dòng biển và vị trí đảo.',
    credit: 'Stick chart, Marshall Islands · Daderot / Ethnologisches Museum · CC0',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Stick_chart_used_for_navigation,_Marshall_Islands,_undated_-_Ethnological_Museum,_Berlin_-_DSC01161.JPG',
    visualNotes: ['Đảo bằng vỏ sò', 'Que mã hóa sóng', 'Tuyến ghi nhớ'],
    quickFacts: [
      { label: 'Dấu hiệu', value: 'Sao · Sóng · Gió · Chim · Mây' },
      { label: 'Công cụ', value: 'La bàn sao · Kamal · La bàn từ' },
      { label: 'Phương pháp', value: 'Ước lượng vị trí · Kiểm tra chéo' },
    ],
    principleTitle: 'Không một dấu hiệu đơn lẻ nào đủ để biết mình đang ở đâu.',
    process: [
      { title: 'Lập tuyến', text: 'Chọn mùa, hướng đích và chuỗi dấu mốc cần gặp.' },
      { title: 'Lấy hướng', text: 'Dùng sao mọc–lặn, Mặt Trời hoặc kim la bàn.' },
      { title: 'Ước lượng trôi', text: 'Kết hợp thời gian, tốc độ, gió, dòng và sóng.' },
      { title: 'Xác nhận', text: 'Đọc chim, mây, sóng phản xạ, độ sâu và hình đất để hiệu chỉnh.' },
    ],
    milestones: [
      { date: 'Truyền thống sống', place: 'Micronesia', text: 'La bàn sao và hướng sóng nối các đảo mà không cần bản đồ giấy.' },
      { date: 'Trước–XV', place: 'Ấn Độ Dương', text: 'Gió mùa, sao Bắc Cực và kamal hỗ trợ các tuyến Ả Rập–Ba Tư.' },
      { date: 'Cuối XI', place: 'Trung Hoa', text: 'Ghi chép sớm còn lại về la bàn dùng trên tàu.' },
      { date: 'Cuối XIII', place: 'Địa Trung Hải', text: 'Hải đồ portolan thể hiện cảng và mạng đường phương vị.' },
    ],
    legacies: ['Thiên văn hàng hải như kỹ năng dự phòng.', 'Hướng la bàn, điểm chuyển hướng và ước lượng vị trí.', 'Kiểm tra chéo nhiều dấu hiệu — nguyên tắc an toàn đến nay.'],
    limits: ['Tri thức rất địa phương; áp sai vùng biển có thể nguy hiểm.', 'Sai số tích lũy khi trời mây hoặc dòng đổi; kinh độ chính xác đến muộn hơn.'],
    sources: [
      { label: 'Library of Congress — hải đồ portolan', url: 'https://guides.loc.gov/nautical-charts/portolan-charts' },
      { label: 'UNESCO — cảnh quan văn hóa Thái Bình Dương', url: 'https://whc.unesco.org/document/10062' },
    ],
  },
  {
    id: 'logic',
    short: 'Logic',
    title: 'Logic & ngôn ngữ học',
    eyebrow: 'Làm cho lời nói và suy luận có thể kiểm tra',
    accent: '#614d7c',
    evidence: 'Mạnh',
    evidenceNote: 'Văn bản và cấu trúc quy tắc có thể khảo cứu trực tiếp; nhiều mẫu suy luận thật sự hợp lệ. Logic ký hiệu và ngôn ngữ học hiện đại đã mở rộng chúng rất xa.',
    summary: 'Logic và ngôn ngữ học cổ tìm cách làm cho suy luận và lời nói có thể phân tích, truyền dạy và phản biện. Pāṇini mô tả tiếng Phạn bằng hàng nghìn quy tắc; Aristotle hệ thống hóa tam đoạn luận; Mặc gia khảo sát tên gọi và phân loại; Nyāya liên hệ lập luận với quan sát và lời chứng. Đây là nhiều truyền thống độc lập, không phải một hệ duy nhất hay phiên bản sớm hoàn chỉnh của lập trình máy tính.',
    image: '/images/08-logic.jpg',
    imagePosition: 'center',
    alt: 'Trang bản thảo Latin Opera Logica của Aristotle khoảng năm 1300 với chữ cái trang trí.',
    credit: 'Aristotle, Opera Logica, khoảng 1300 · Columbia University · Public domain',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Aristotle_Opera_Logica.jpg',
    visualNotes: ['Định nghĩa', 'Tiền đề', 'Suy luận'],
    quickFacts: [
      { label: 'Đơn vị', value: 'Từ · Mệnh đề · Quy tắc' },
      { label: 'Kiểm tra', value: 'Phản ví dụ · Mâu thuẫn · Nhập nhằng' },
      { label: 'Di sản', value: 'Ngữ pháp · Logic · Biện luận' },
    ],
    principleTitle: 'Kết luận tốt cần từ ngữ rõ và bước suy luận hợp lệ.',
    process: [
      { title: 'Định nghĩa', text: 'Làm rõ thuật ngữ và phân biệt các loại đối tượng.' },
      { title: 'Đặt tiền đề', text: 'Nêu phạm vi áp dụng và quan hệ cần chứng minh.' },
      { title: 'Suy luận', text: 'Áp dụng mẫu hay quy tắc biến đổi đã chấp nhận.' },
      { title: 'Phản biện', text: 'Tìm phản ví dụ, mâu thuẫn hoặc nhập nhằng rồi sửa.' },
    ],
    milestones: [
      { date: 'V–IV TCN', place: 'Ấn Độ', text: 'Aṣṭādhyāyī của Pāṇini dùng quy tắc và siêu quy tắc mô tả tiếng Phạn.' },
      { date: 'IV TCN', place: 'Athens', text: 'Aristotle xây hệ tam đoạn luận dựa trên quan hệ giữa thuật ngữ.' },
      { date: 'IV–III TCN', place: 'Trung Hoa', text: 'Mặc gia phân tích tên gọi, giống–khác và suy luận tương tự.' },
      { date: 'Đầu Công nguyên', place: 'Ấn Độ', text: 'Nyāya trình bày suy luận năm thành phần và các nguồn tri thức.' },
    ],
    legacies: ['Ngữ pháp dựa trên quy tắc và phân tích hình thái–cú pháp.', 'Phân biệt tiền đề, kết luận, tính hợp lệ và tính đúng.', 'Định nghĩa, phản ví dụ và nhận diện ngụy biện.'],
    limits: ['Logic thuật ngữ Aristotle không đủ cho mọi quan hệ và toán học hiện đại.', 'Một ngữ pháp gắn với một ngôn ngữ không phải mô hình phổ quát cho mọi tiếng.'],
    sources: [
      { label: 'Stanford Encyclopedia — logic cổ đại', url: 'https://plato.stanford.edu/entries/logic-ancient/' },
      { label: 'Stanford Encyclopedia — Mặc gia', url: 'https://plato.stanford.edu/entries/mohist-canons/' },
      { label: 'Stanford Encyclopedia — logic Ấn Độ', url: 'https://plato.stanford.edu/entries/logic-india/' },
    ],
  },
  {
    id: 'quang-co',
    short: 'Quang–cơ',
    title: 'Quang học & cơ học',
    eyebrow: 'Tách hiện tượng thành tia, lực và khoảng cách',
    accent: '#b06e2c',
    evidence: 'Mạnh',
    evidenceNote: 'Quy luật tia trong miền thích hợp, mômen và lực nổi đều tái lập tốt. Chúng là mô hình giới hạn, không mô tả hoàn chỉnh mọi ánh sáng và chuyển động.',
    summary: 'Quang học cổ nghiên cứu ánh sáng, ảnh và thị giác; cơ học cổ nghiên cứu cân bằng, lực, máy đơn giản và vật nổi. Buồng tối lỗ kim, gương, đòn bẩy, ròng rọc và bình nước giúp học giả dùng hình học cùng dụng cụ để cô lập hiện tượng. Thành tựu bền vững gồm mô hình tia sáng, phản xạ, mômen đòn bẩy và thủy tĩnh học; quang học và động lực học hiện đại đã mở rộng rất nhiều.',
    image: '/images/09-optics.jpg',
    imagePosition: 'center',
    alt: 'Sơ đồ mắt theo Ibn al-Haytham trong bản sao Kitab al-Manazir, thể hiện cấu tạo và đường nhìn.',
    credit: 'Ibn al-Haytham, Kitab al-Manazir · Süleymaniye Library · Public domain',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Alhazen1652.png',
    visualNotes: ['Tia sáng', 'Mắt nhận ánh sáng', 'Hình học thị giác'],
    quickFacts: [
      { label: 'Quang học', value: 'Tia · Gương · Lỗ kim · Khúc xạ' },
      { label: 'Cơ học', value: 'Mômen · Trọng tâm · Lực nổi' },
      { label: 'Dụng cụ', value: 'Buồng tối · Cân · Đòn bẩy' },
    ],
    principleTitle: 'Cô lập hiện tượng, lý tưởng hóa, rồi đo.',
    process: [
      { title: 'Cô lập', text: 'Dùng lỗ nhỏ, gương, cân, đòn bẩy hoặc bình nước.' },
      { title: 'Lý tưởng hóa', text: 'Biểu diễn bằng đường, góc, khoảng cách, lực và trọng lượng.' },
      { title: 'Định lượng', text: 'Lập quan hệ cho góc phản xạ, mômen hay lực nổi.' },
      { title: 'Thử lại', text: 'So dự đoán với quan sát và sửa mô hình khi lệch.' },
    ],
    milestones: [
      { date: 'IV–III TCN', place: 'Trung Hoa', text: 'Mặc gia mô tả ảnh đảo qua lỗ nhỏ và tác dụng của cánh tay đòn.' },
      { date: '≈ 300 TCN', place: 'Alexandria', text: 'Euclid dùng hình học tia và góc nhìn; mô hình tia phát từ mắt nay lỗi thời.' },
      { date: 'III TCN', place: 'Syracuse', text: 'Archimedes trình bày đòn bẩy, trọng tâm và lực đẩy chất lỏng.' },
      { date: '≈ 1021', place: 'Cairo', text: 'Ibn al-Haytham dùng thí nghiệm để chỉ ra ánh sáng đi vào mắt.' },
    ],
    legacies: ['Sơ đồ tia và buồng tối trong quang học hình học.', 'Mômen lực, trọng tâm và máy đơn giản trong kỹ thuật.', 'Nguyên lý Archimedes trong đo tỷ trọng và thiết kế tàu.'],
    limits: ['Mô hình tia phát từ mắt và một số cơ chế khúc xạ cổ đã lỗi thời.', 'Cơ học cổ chưa có quán tính, động lực học và bảo toàn năng lượng đầy đủ.'],
    sources: [
      { label: 'UNESCO — phương pháp của Ibn al-Haytham', url: 'https://courier.unesco.org/en/articles/ibn-al-haythams-scientific-method' },
      { label: 'MacTutor — Archimedes', url: 'https://mathshistory.st-andrews.ac.uk/Biographies/Archimedes/' },
    ],
  },
  {
    id: 'sinh-thai',
    short: 'Sinh thái',
    title: 'Sinh thái bản địa',
    eyebrow: 'Tri thức gắn với cộng đồng và nơi chốn',
    accent: '#3f7458',
    evidence: 'Vừa',
    evidenceNote: 'Nhiều thực hành cụ thể có bằng chứng khảo cổ, sinh thái và nghiên cứu trường hợp tốt; cơ chế và hiệu quả thay đổi theo vùng. Việc sử dụng cần đồng thuận và tôn trọng quyền tri thức.',
    summary: 'Tri thức sinh thái bản địa là những hệ hiểu biết động, gắn với một cộng đồng và lãnh thổ cụ thể — không phải kho “bí quyết cổ” đồng nhất. Quan sát nhiều thế hệ liên kết mùa, đất, nước, lửa và hành vi loài với quy tắc khai thác. Kiến thức được lưu bằng ngôn ngữ, lịch mùa, truyện kể và thực hành. Áp dụng ở nơi khác phải hợp tác với cộng đồng nắm giữ và kiểm chứng theo bối cảnh.',
    image: '/images/10-ecology.jpg',
    imagePosition: 'center',
    alt: 'Minh họa vườn bản địa châu Mỹ thế kỷ XVI với nhiều loài cây được trồng xen.',
    credit: 'Histoire Naturelle des Indes, cuối thế kỷ XVI · CC0',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Indian_garden_from_Histoire_Naturelle_des_Indes.jpg',
    visualNotes: ['Đa tầng tán', 'Nhiều loài', 'Quan sát theo mùa'],
    quickFacts: [
      { label: 'Đơn vị', value: 'Cộng đồng · Lãnh thổ · Mùa' },
      { label: 'Truyền đạt', value: 'Thực hành · Ngôn ngữ · Lịch mùa' },
      { label: 'Điều kiện', value: 'Đồng thuận · Quyền tri thức · Bối cảnh' },
    ],
    principleTitle: 'Quan sát dài hạn trở thành quy tắc quản lý thích nghi.',
    process: [
      { title: 'Đọc dấu hiệu', text: 'Theo dõi mùa, loài, đất, nước và thời tiết tại chỗ.' },
      { title: 'Đối chiếu', text: 'Kiểm nghiệm kinh nghiệm trong cộng đồng qua thực hành.' },
      { title: 'Đặt quy tắc', text: 'Quy định thời điểm, nơi, lượng khai thác và luân phiên.' },
      { title: 'Thích nghi', text: 'Theo dõi hệ sinh thái rồi điều chỉnh khi điều kiện đổi.' },
    ],
    milestones: [
      { date: 'Truyền thống sống', place: 'Bắc Australia', text: 'Đốt văn hóa quy mô nhỏ, đúng mùa và phù hợp từng Country.' },
      { date: 'Truyền thống sống', place: 'Bắc Thái Lan', text: 'Canh tác luân phiên, đa cây và thời kỳ bỏ hóa theo quy tắc cộng đồng.' },
      { date: 'Trước–nay', place: 'Hawaiʻi', text: 'Ahupuaʻa quản lý dải tài nguyên từ núi, nước ngọt đến biển.' },
      { date: '2004 / truyền khẩu', place: 'Biển Andaman', text: 'Tri thức Moken về dấu hiệu sóng lớn hỗ trợ sơ tán khi nước rút bất thường.' },
    ],
    legacies: ['Đốt văn hóa do cộng đồng bản địa lãnh đạo.', 'Lịch mùa và giám sát đa dạng sinh học cộng đồng.', 'Quản lý tổng hợp lưu vực–bờ biển và duy trì giống địa phương.'],
    limits: ['Thực hành hiệu quả ở nơi này không tự động phù hợp nơi khác.', 'Tri thức bản địa không mặc nhiên luôn đúng; nghiên cứu cũng không được tách nó khỏi quyền và bối cảnh.'],
    sources: [
      { label: 'CSIRO — cultural burning', url: 'https://www.csiro.au/en/news/all/articles/2021/october/hazard-reduction-burn' },
      { label: 'NOAA — hệ ahupuaʻa', url: 'https://sanctuaries.noaa.gov/bwet/hawaii/ahupuaa.html' },
      { label: 'UNESCO–IPBES — tri thức bản địa', url: 'https://www.unesco.org/en/links/ipbes' },
    ],
  },
  {
    id: 'am-hoc',
    short: 'Âm học',
    title: 'Âm học & nhạc luật',
    eyebrow: 'Khi tỷ lệ số trở thành âm thanh',
    accent: '#91526d',
    evidence: 'Mạnh',
    evidenceNote: 'Quan hệ giữa tần số, chiều dài dây, sức căng, cộng hưởng và phổ âm được xác nhận định lượng. Điều này không biến thị hiếu hay ý nghĩa cảm xúc thành quy luật phổ quát.',
    summary: 'Âm học và nhạc luật cổ nối quan sát vật lý với tổ chức âm nhạc. Dây ngắn hoặc căng hơn thường cho âm cao hơn; vật rung truyền dao động; hộp đàn và không gian thay đổi độ lớn lẫn âm sắc. Từ đàn một dây Hy Lạp, chuông đồng Trung Hoa, raga–tala Ấn Độ đến trước tác của al-Fārābī, người xưa xây thang âm, nhịp và kỹ thuật chế tác. Vật lý đo được; cảm giác thuận tai vẫn phụ thuộc văn hóa.',
    image: '/images/11-acoustics.jpg',
    imagePosition: 'center',
    alt: 'Tranh khắc Pythagoras thử cao độ bằng chuông, cốc, đàn một dây và ống hơi.',
    credit: 'Franchino Gaffurio, Theorica musicae, 1492 · BnF · Public domain',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Gaffurio_Pythagoras.png',
    visualNotes: ['Tỷ lệ dây', 'Nguồn rung', 'Cộng hưởng'],
    quickFacts: [
      { label: 'Đại lượng', value: 'Tần số · Chiều dài · Sức căng' },
      { label: 'Hệ thống', value: 'Quãng · Thang âm · Nhịp' },
      { label: 'Nhạc cụ', value: 'Dây · Ống · Màng · Chuông' },
    ],
    principleTitle: 'Dao động vật lý được văn hóa tổ chức thành âm nhạc.',
    process: [
      { title: 'Tạo rung', text: 'Gảy dây, gõ màng hay chuông, hoặc thổi cột khí.' },
      { title: 'Định cao độ', text: 'Chiều dài, sức căng, khối lượng và hình dạng đặt tần số.' },
      { title: 'Cộng hưởng', text: 'Hộp đàn và không gian khuếch đại hoặc lọc tần số.' },
      { title: 'Tổ chức', text: 'Tai và truyền thống xếp âm thành quãng, thang, nhịp, điệu thức.' },
    ],
    milestones: [
      { date: 'Truyền thống cổ', place: 'Hy Lạp', text: 'Đàn một dây minh họa tỷ lệ 2:1 cho quãng tám và 3:2 cho quãng năm.' },
      { date: '433 TCN', place: 'Hồ Bắc', text: 'Bộ 65 chuông Hầu tước Ất thể hiện kỹ thuật đúc và lên cao độ cao.' },
      { date: 'Đầu Công nguyên', place: 'Ấn Độ', text: 'Nāṭyaśāstra hệ thống hóa âm, nhịp và mỹ học trình diễn.' },
      { date: 'Thế kỷ X', place: 'Baghdad', text: 'Al-Fārābī bàn về âm học, quãng, nhạc cụ và tiết tấu.' },
    ],
    legacies: ['Tỷ số tần số và phép tính lên dây.', 'Thiết kế dây, ống, màng, chuông và hộp cộng hưởng.', 'Hệ điệu thức và mô hình tiết tấu trong truyền dạy, sáng tác.'],
    limits: ['Hệ Pythagore không khép kín hoàn toàn và khác bình quân luật.', '“Thuận tai” hay liên hệ vũ trụ không phải hệ quả phổ quát của tỷ lệ số.'],
    sources: [
      { label: 'The Met — âm nhạc và nghệ thuật Trung Hoa', url: 'https://www.metmuseum.org/essays/music-and-art-of-china' },
      { label: 'Encyclopaedia Iranica — al-Fārābī và âm nhạc', url: 'https://www.iranicaonline.org/articles/farabi-v/' },
    ],
  },
  {
    id: 'than-tam',
    short: 'Thân–tâm',
    title: 'Rèn luyện thân–tâm',
    eyebrow: 'Tư thế, hơi thở, chú ý và phản hồi',
    accent: '#786647',
    evidence: 'Hỗn hợp',
    evidenceNote: 'Một số chương trình cụ thể cho thấy lợi ích nhỏ hoặc vừa với thăng bằng, đau lưng, căng thẳng hay giấc ngủ. Kết quả không đồng đều và không thay thế điều trị chuẩn.',
    summary: 'Rèn luyện thân–tâm bao gồm nhiều truyền thống khác nhau như yoga, thiền, đạo dẫn–dưỡng sinh và thái cực quyền. Chúng phối hợp tư thế hoặc chuyển động, nhịp thở, chú ý và luyện tập lặp lại. Khi hiện đại hóa, một số thành phần trở thành vận động nhẹ, bài tập thăng bằng hoặc chương trình chánh niệm. Không nên xem khí, prāṇa hay luân xa là năng lượng hoặc cấu trúc giải phẫu đã được chứng minh.',
    image: '/images/12-mind-body.jpg',
    imagePosition: 'center',
    alt: 'Mảnh tranh lụa Mã Vương Đôi thời Tây Hán mô tả nhiều người thực hiện các tư thế đạo dẫn.',
    credit: 'Đạo Dẫn Đồ, Mã Vương Đôi, thế kỷ II TCN · Public domain',
    imageSource: 'https://commons.wikimedia.org/wiki/File:Qigong_taiji_meditation.jpg',
    visualNotes: ['Tư thế', 'Hơi thở', 'Chú ý'],
    quickFacts: [
      { label: 'Thành phần', value: 'Chuyển động · Thở · Chú ý' },
      { label: 'Ứng dụng', value: 'Thăng bằng · Thư giãn · Linh hoạt' },
      { label: 'Nguyên tắc', value: 'Tăng dần · Phù hợp thể trạng' },
    ],
    principleTitle: 'Kỹ năng tự điều chỉnh được hình thành bằng luyện tập lặp lại.',
    process: [
      { title: 'Chọn bài', text: 'Xác định mục tiêu và tư thế phù hợp thể trạng.' },
      { title: 'Điều hòa', text: 'Giữ hơi thở tự nhiên, đều; tránh ép thở hoặc nín thở.' },
      { title: 'Đặt chú ý', text: 'Theo dõi cảm giác, hơi thở hay chuyển động rồi quay lại khi xao lãng.' },
      { title: 'Nhận phản hồi', text: 'Tăng dần thời lượng và điều chỉnh khi khó chịu.' },
    ],
    milestones: [
      { date: 'Giữa thiên niên kỷ I TCN', place: 'Nam Á', text: 'Nhiều truyền thống phát triển thiền, hơi thở và tiết chế thân thể.' },
      { date: '168 TCN', place: 'Trường Sa', text: 'Đạo Dẫn Đồ là chứng cứ vật chất sớm về vận động dưỡng sinh.' },
      { date: 'Đầu Công nguyên', place: 'Ấn Độ', text: 'Yoga-sūtra hệ thống hóa đạo đức, tư thế, hơi thở, tập trung và thiền.' },
      { date: 'Từ thế kỷ XVII', place: 'Trung Hoa', text: 'Tư liệu rõ hơn về thái cực quyền như võ thuật phối hợp thân–ý–thở.' },
    ],
    legacies: ['Vận động nhẹ, linh hoạt và thăng bằng từ yoga hoặc thái cực.', 'Kỹ thuật chú ý hơi thở trong chương trình chánh niệm.', 'Ứng dụng bổ trợ có mục tiêu và hướng dẫn rõ.'],
    limits: ['Chưa có bằng chứng xác nhận khí, prāṇa, luân xa hay kinh mạch như vật thể vật lý.', 'Nghiên cứu không đồng nhất; luyện sai có thể gây chấn thương hoặc trải nghiệm khó chịu.'],
    sources: [
      { label: 'NCCIH — yoga: hiệu quả và an toàn', url: 'https://www.nccih.nih.gov/health/yoga-effectiveness-and-safety' },
      { label: 'NCCIH — thiền và chánh niệm', url: 'https://www.nccih.nih.gov/health/meditation-and-mindfulness-effectiveness-and-safety' },
      { label: 'NCCIH — thái cực quyền', url: 'https://www.nccih.nih.gov/health/tai-chi-what-you-need-to-know' },
    ],
  },
];
